name: Generate Snake Game

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          color_snake: orange
          color_dots: '#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9'